
### Request
GET http://localhost:3000/health

### getting all users
GET http://localhost:8000/api/users

###
GET httP://localhost:8000/api/users/devngec@gmail.com
Content-Type: application/json

###
GET httP://localhost:8000/api/users/byID/1011
Content-Type: application/json

###
POST httP://localhost:8000/api/users/login
Content-Type: application/json

{
    "Email":"simogatuma22@gmail.com", 
    "Password":"simon"
}

### REGISTERING A USER
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
    "Firstname":"Robinson",
    "Lastname":"Ngecu",
    "Address":"Nyeri",
    "PositionID":"4",
    "Gender":"Male",
    "Schedule":"Morning shift",
    "BirthDate":"1990-01-12",
    "ContactInfo":"0705957078",
    "PhotoURL":"https://wallpaperaccess.com/full/1347872.jpg",
    "Email":"simogatuma24@gmail.com",
    "Password":"simon"
}

###UPDATING USER BY ID
PUT http://localhost:8000/api/users/update/7
Content-Type: application/json

{
    "Firstname":"simon",
    "Lastname":"kamau",
    "Address":"Nyeri",
    "PositionID":"2",
    "Gender":"Male",
    "Schedule":"Morning shift",
    "BirthDate":"1990-01-12",
    "ContactInfo":"0705957078",
    "PhotoURL":"https://res.cloudinary.com/diyuy63ue/image/upload/v1712007641/pxysns9ctrpnxjzfb1jx.jpg",
    "Email":"simogatuma22@gmail.com",
    "Password":"simon"
}

### DELETING USERS
DELETE http://localhost:8000/api/users/delete/1
Content-Type: application/json


### creating a position
POST http://localhost:8000/api/positions/register
Content-Type: application/json

{
    "Position":"Admin",
    "Basic_Salary":"120000"
}
### updating a position
PUT http://localhost:8000/api/positions/update/2
Content-Type: application/json

{
    "Position":"Admin",
    "Basic_Salary":"120000"
}


### getting all positions
GET http://localhost:8000/api/Positions


###
GET http://localhost:8000/api/Positions/6


### deleting position
DELETE http://localhost:8000/api/positions/delete/1
Content-Type: application/json



### creating a new shedule
POST http://localhost:8000/api/Schedules/register
Content-Type: application/json

{
    "Days": "1",
    "StartTime": "2024-03-18 09:00:00", 
    "EmployeeID":"1011",
    "EndTime": "2024-03-18 00:00:00" 
}

### getting all shedules
GET http://localhost:8000/api/Schedules


### deleting schedules
DELETE http://localhost:8000/api/Schedules/delete/4
Content-Type: application/json

###UPDATING SCHEDULE
PUT http://localhost:8000/api/Schedules/update/2
Content-Type: application/json


{
    "Days": "7",
    "StartTime": "2024-03-18 09:00:00", 
    "EmployeeID":"2",
    "EndTime": "2024-03-18 00:00:00" 
}


### creating a new attendance
POST http://localhost:8000/api/Attendance/record
Content-Type: application/json

{
    "Date": "2024-03-18",
    "EmployeeID": "2",
    "TimeIn": "2024-03-18T09:00:00" 
}



### geting all attendance
GET http://localhost:8000/api/Attendance

###
GET http://localhost:8000/api/Attendance/5

### update attendance
PUT  http://localhost:8000/api/Attendance/update/1
Content-Type: application/json

{
    "TimeOut": "2024-03-18,00:00:00" 
}

### delete attendance
DELETE http://localhost:8000/api/Attendance/delete/2
Content-Type: application/json



### creating a deduction
POST http://localhost:8000/api/Deduction/register
Content-Type: application/json

{
    "Description": "Nhi",
    "Amount": "3339.00",
    "EmployeeID":"7"
}

### getting all deductions
GET http://localhost:8000/api/Deduction


#### updating deduction
PUT http://localhost:8000/api/Deduction/update/1
Content-Type: application/json

{
    "Description": "added a new description",
    "Amount": "50000.00"
}
### deleting deduction
DELETE http://localhost:8000/api/Deduction/delete/8

###gettind deduction by id
GET http://localhost:8000/api/Deduction/employee/7



### creating advanced cash
POST http://localhost:8000/api/Advance/register
Content-Type: application/json

{
   "Date": "2024-03-18",
    "Amount": "299.00",
    "EmployeeID":"2"
}

### getting all advance
GET http://localhost:8000/api/Advance

### deleting advance cash
DELETE http://localhost:8000/api/Advance/delete/4

### updating advance cash
PUT http://localhost:8000/api/Advance/update/2
Content-Type: application/json

{
   "Date": "2024-03-18",
    "Amount": "60000.00"
}

### ADDING OVERTIME
POST http://localhost:8000/api/Overtime/register
Content-Type: application/json

{
   "Date": "2024-03-18",
    "Hours": "2",
    "Minutes": "59",
    "Rate": "50000.00"
}
### GETTING OVERTIME BY ID
GET http://localhost:8000/api/Overtime/1

### GETTING ALL OVERTIMES
GET http://localhost:8000/api/Overtime

### DELETING OVERTIME
DELETE http://localhost:8000/api/Overtime/delete/1

#### UPDATING OVERTIME
PUT http://localhost:8000/api/Overtime/update/2
Content-Type: application/json

{
   "Date": "2024-03-18",
    "Hours": "2",
    "Minutes": "69",
    "Rate": "50000.00"
}

###
POST http://localhost:8000/api/Payroll/register
Content-Type:application/json

{
    "EmployeeID":"4"
}

###
GET http://localhost:8000/api/Payrolls

###
GET http://localhost:8000/api/Payrolls/7

