
### Request
GET http://localhost:8000/health

### getting all users
GET http://localhost:8000/api/users

###
POST httP://localhost:8000/api/users
Content-Type: application/json

{
    "Email":"simon@gmail.com"
}

###
POST httP://localhost:8000/api/users/login
Content-Type: application/json

{
    "Email":"simogatuma21@gmail.com",
    "Password":"simonkamau"
}

###
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
    "Firstname":"leah",
    "Lastname":"Nyambura",
    "Address":"Nyeri",
    "BirthDate":"1990-01-12",
    "ContactInfo":"0705957078",
    "Admin":"1",
    "PhotoURL":"https://example.com/photo.jpgsimon",
    "Email":"simogatuma21@gmail.com",
    "Password":"leah nyambura2314@"
}

###
PUT http://localhost:8000/api/users/update/51
Content-Type: application/json

{
    "Firstname":"kimani",
    "Lastname":"kimani",
    "Address":"Nyeri",
    "BirthDate":"1990-01-12",
    "ContactInfo":"0759717794",
    "Admin":"1",
    "PositionID":"1",
    "ScheduleID":"1",
    "PhotoURL":"https://example.com/photo.jpgsimon",
    "Email":"simon@gmail.com"
  
}
###
DELETE http://localhost:8000/api/users/delete/53
Content-Type: application/json





### creating a position
POST http://localhost:8000/api/positions/register
Content-Type: application/json

{
    "Title":"kofware",
    "Basic_Salary":"60000"
}
### updating a position
PUT http://localhost:8000/api/positions/update/4
Content-Type: application/json

{
    "Title":"Sofware",
    "Basic_Salary":"70000"
}


### getting all positions
GET http://localhost:8000/api/Positions


### deleting position
DELETE http://localhost:8000/api/positions/delete/2
Content-Type: application/json



### creating a new shedule
POST http://localhost:8000/api/Schedules/register
Content-Type: application/json

{
    "Schedules_name": "Nigh Shift",
    "StartTime": "2024-03-18 09:00:00", 
    "EndTime": "2024-03-18 00:00:00" 
}

### getting all shedules
GET http://localhost:8000/api/Schedules

### deleting schedules
DELETE http://localhost:8000/api/Schedules/delete/4
Content-Type: application/json

###
PUT http://localhost:8000/api/Schedules/update/3
Content-Type: application/json


{
    "Schedules_name": "Night Shift",
    "StartTime": "2024-03-18 09:00:00", // Adjust the date as needed
    "EndTime": "2024-03-18 00:00:00" // Adjust the date as needed
}
